server.port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/minibooking?replicaSet=rs0
kafka.bootstrap-servers: localhost:9092
topics:
  bookingRequested: booking.requested.v1
  bookingLifecycle: booking.lifecycle.v1
